/**
 * Doc code that does not run in this repo, kept byte-exact from
 * https://docs.copilotkit.ai/pydantic-ai/human-in-the-loop/governed-actions
 * and rendered as text on the route page. Not imported by any demo.
 */

export const USE_INTERRUPT_SNIPPET = "import { useEffect } from \"react\";\nimport { useInterrupt } from \"@copilotkit/react-core/v2\";\n\nfunction GovernedActionApproval() {\n  useInterrupt({\n    render: ({ interrupt, resolve, cancel }) => {\n      const action = interrupt?.metadata?.action as GovernedAction | undefined;\n\n      if (!action) {\n        return null;\n      }\n\n      return (\n        <GovernedActionCard\n          action={action}\n          onApprove={() =>\n            resolve({\n              approved: true,\n              actionId: action.id,\n              reference: action.reference,\n            })\n          }\n          onReject={() =>\n            resolve({\n              approved: false,\n              actionId: action.id,\n              reference: action.reference,\n            })\n          }\n          onBlock={() => cancel()}\n        />\n      );\n    },\n  });\n\n  return null;\n}\n\nfunction GovernedActionCard({\n  action,\n  onApprove,\n  onReject,\n  onBlock,\n}: {\n  action: GovernedAction;\n  onApprove: () => void;\n  onReject: () => void;\n  onBlock: () => void;\n}) {\n  useEffect(() => {\n    if (action.verdict === \"allow\") onApprove();\n    if (action.verdict === \"deny\") onBlock();\n  }, [action.id, action.verdict]);\n\n  const status =\n    action.verdict === \"allow\"\n      ? \"Allowed by policy\"\n      : action.verdict === \"deny\"\n        ? \"Blocked by policy\"\n        : \"User approval required\";\n\n  return (\n    <section className=\"rounded-lg border p-4 shadow-sm\">\n      <div className=\"space-y-1\">\n        <p className=\"text-sm font-medium\">{status}</p>\n        <h3 className=\"text-base font-semibold\">{action.summary}</h3>\n        <p className=\"text-sm text-muted-foreground\">Tool: {action.tool}</p>\n        <p className=\"text-sm text-muted-foreground\">\n          Reference: {action.reference}\n        </p>\n      </div>\n\n      <pre className=\"mt-3 overflow-auto rounded bg-muted p-3 text-xs\">\n        {JSON.stringify(action.arguments, null, 2)}\n      </pre>\n\n      {action.verdict === \"require_approval\" && (\n        <div className=\"mt-4 flex gap-2\">\n          <button type=\"button\" onClick={onApprove}>\n            Approve and run\n          </button>\n          <button type=\"button\" onClick={onReject}>\n            Reject\n          </button>\n        </div>\n      )}\n    </section>\n  );\n}\n";

export const HANDLE_APPROVAL_SNIPPET = "type ApprovalResponse = {\n  approved: boolean;\n  actionId: string;\n  reference: string;\n};\n\nasync function handleApproval(action: GovernedAction, response: ApprovalResponse) {\n  if (\n    response.approved &&\n    response.actionId === action.id &&\n    response.reference === action.reference\n  ) {\n    return executeSideEffect(action.tool, action.arguments);\n  }\n\n  return {\n    skipped: true,\n    reason: \"The user did not approve this action.\",\n  };\n}\n";
